import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers, { ProvidersProps } from "@/app/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<ProvidersProps>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-4 max-w-xl">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
